### ISSUE TITLE
Docker build is failing with error

### ISSUE THREAD

**Issue by shubham149** [alvarobartt/vertex-ai-huggingface#1]
On following this jupyter notebook https://github.com/alvarobartt/vertex-ai-huggingface/blob/main/online-prediction/04-from-hub-to-vertex-ai-gpu.ipynb, I am getting the below error:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/usr/lib/python3.8/subprocess.py:842: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
Traceback (most recent call last):
  File "push.py", line 5, in <module>
    local_model = LocalModel.build_cpr_model(
  File "/home/shubham_agrawal_harness_io/.local/lib/python3.8/site-packages/google/cloud/aiplatform/prediction/local_model.py", line 381, in build_cpr_model
    _ = build.build_image(
  File "/home/shubham_agrawal_harness_io/.local/lib/python3.8/site-packages/google/cloud/aiplatform/docker_utils/build.py", line 548, in build_image
    raise DockerError(error_msg, command, return_code)
google.cloud.aiplatform.docker_utils.errors.DockerError: ('\nDocker failed with error code 1.\nCommand: docker build -t us-central1-docker.pkg.dev/ml/testmodel/test:0.1 --rm -f- ./src_dir\n', ['docker', 'build', '-t', 'us-central1-docker.pkg.dev/ml/testmodel/test:0.1', '--rm', '-f-', './src_dir'], 1)
```

Can you please provide some suggestions to fix the docker build

**Comment by alvarobartt** [comment]
Hi @shubham149, sure! Indeed that may be related to Docker itself, could you check the Docker logs for that build? You'll get more details on why the build process failed i.e. checking the layer history as `docker history us-central1-docker.pkg.dev/ml/testmodel/test:0.1`?

**Comment by alvarobartt** [comment]
Also it's hard to debug as the `docker build` is under some layers automatically handled by `google-cloud-aiplatform` so the issue may be hard to debug :/ The easiest IMO is to use Docker Desktop on the latest version to use the `Builds` tab (still in beta), and track the logs whenever you run that code cell, so as to see the building logs in real-time (or once it succeeds/fails), see screenshot below.

<img width="1624" alt="image" src="https://github.com/alvarobartt/vertex-ai-huggingface/assets/36760800/b533559b-872d-468b-9a26-cd97661bebfa">

**Comment by shubham149** [comment]
Thanks a lot @alvarobartt
It was "No space left on device" issue. Above suggestion helped me in debugging this issue.

**Comment by alvarobartt** [comment]
Glad that you fixed it! Also FYI I built a Python package, [`alvarobartt/vertex-ai-huggingface-inference-toolkit`](https://github.com/alvarobartt/vertex-ai-huggingface-inference-toolkit), in order to improve the model deployment process in Vertex AI with models from the Hugging Face Hub, in case you want to give it a try! 🤗
