### ISSUE TITLE
Uploading quantized models to VertexAI from HuggingFace 🤗 Hub?

### ISSUE THREAD

**Issue by AryaStark13** [alvarobartt/vertex-ai-huggingface#2]
Hi,

I liked your implementation to easily deploy models to a VertexAI Endpoint for serving. I was wondering how could I use quantized models for this?

For example, I want to use the [TencentARC/Mistral_Pro_8B_v0.1](https://huggingface.co/TencentARC/Mistral_Pro_8B_v0.1) model for inference (which does not have a dedicated API Inference). The model consists of 8B+ parameters which requires ~16-18 GB of memory for inference using BF16. I was wondering if we could quanitze the model and then upload it to the GCS Bucket and register it in the Google Cloud Registry without needing to save it locally 🤔

Let me know if you have an idea on how we could implement this. 

Thanks,
Arihant Sheth.

**Comment by alvarobartt** [comment]
Hi here @AryaStark13, indeed to do so I put together https://github.com/alvarobartt/vertex-ai-huggingface-inference-toolkit so that anyone can just define the `HF_HUB_ID` as an environment variable without having to pull anything locally, since everything will be pulled within the Vertex AI Endpoint on start up. And then you can just set the `HF_MODEL_KWARGS` as you would set those via the `AutoModelForCausalLM.from_pretrained` method. 👍🏻

Not sure if this is what you mean, but this way you avoid having to download the model locally to push it to GCS, and can run quantized inference via kwargs when loading the model.

Here's the code reference in case that's useful to you, otherwise please let me know!

```python
# pip install vertex-ai-huggingface-inference-toolkit>=0.0.2
from vertex_ai_huggingface_inference_toolkit import TransformersModel

model = TransformersModel(
    project_id="my-project",
    location="us-east1",
    extra_requirements=["flash-attn --no-build-isolation"],
    environment_variables={
        "HF_HUB_ID": "TencentARC/Mistral_Pro_8B_v0.1",
        "HF_MODEL_KWARGS": {"torch_dtype": "bfloat16", "attn_implementation": "flash_attention_2"},
        "HF_TASK": "text-generation",
    },
)
```

On top of that you can add e.g. `load_in_4bit: True` or `load_in_8bit: True`, to run the inference on top of a quantized model in 4 and 8 bits, respectively.

**Comment by AryaStark13** [comment]
Wow, this is great! Thanks, I'll check the repo out. I'll be diving deep into deploying HF Models for inference in the next few weeks. Let me know if you're looking to collaborating on maintaining and adding more functionalities to the repo.

**Comment by alvarobartt** [comment]
Other than that, if you don't mind pulling those models locally, you can quantize those either locally or via free Colab IINM, using a similar script as the one below, and then pushing the model to the Hub as you would normally do, but now with the quantized weights that take less disk space.

```python
from transformers import BitsAndBytesConfig

nf4_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4")
model_nf4 = AutoModelForCausalLM.from_pretrained("TencentARC/Mistral_Pro_8B_v0.1", quantization_config=nf4_config)
model_nf4.push_to_hub("Mistral_Pro_8B_v0.1-bnb-4bit")
```

**Comment by alvarobartt** [comment]
> Wow, this is great! Thanks, I'll check the repo out. I'll be diving deep into deploying HF Models for inference in the next few weeks. Let me know if you're looking to collaborating on maintaining and adding more functionalities to the repo.

That's great, let me know if you have any other doubt / issue! And I have a bunch of Vertex AI related scripts, pipelines, and such; but have low bandwidth atm, but planning to add those to this repository, at least the Kubeflow pipelines for fine-tuning LLMs, and a couple more extra things!

**Comment by AryaStark13** [comment]
> Other than that, if you don't mind pulling those models locally, you can quantize those either locally or via free Colab IINM, using a similar script as the one below, and then pushing the model to the Hub as you would normally do, but now with the quantized weights that take less disk space.
> 
> ```python
> from transformers import BitsAndBytesConfig
> 
> nf4_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4")
> model_nf4 = AutoModelForCausalLM.from_pretrained("TencentARC/Mistral_Pro_8B_v0.1", quantization_config=nf4_config)
> model_nf4.push_to_hub("Mistral_Pro_8B_v0.1-bnb-4bit")
> ```

I'm still on basc consumer-grade hardware with 8 Gigs of RAM and 4 Gigs of VRAM, but I'll try this out someday 🤞

**Comment by AryaStark13** [comment]
> > Wow, this is great! Thanks, I'll check the repo out. I'll be diving deep into deploying HF Models for inference in the next few weeks. Let me know if you're looking to collaborating on maintaining and adding more functionalities to the repo.
> 
> That's great, let me know if you have any other doubt / issue! And I have a bunch of Vertex AI related scripts, pipelines, and such; but have low bandwidth atm, but planning to add those to this repository, at least the Kubeflow pipelines for fine-tuning LLMs, and a couple more extra things!

I'll let you know as I go through the implementation by posting on the other repo directly. 

If you're busy for now, I'd love to help you in adding them. We can get on a meet to discss further?
